---
- name: Automatisation de la configuration du Captive Portal sur pfSense
  hosts: pfsense
  become: yes
  roles: 
    - role: users
    - role: SSLConf
    - role: DNSResolver
    - role: CaptivePortal
